---
title: "Inference for Two-Way Tables"
author: "Chapter 8, Lab 2"
date: "OpenIntro Biostatistics"

fontsize: 11pt
geometry: margin=1in

output:
  pdf_document:
    includes:
      in_header: ../../header.tex
    fig_width: 5
    fig_height: 3.5
---

\begin{small}
	
	\textbf{Topics}
	\begin{itemize}
	  \item The $\chi^2$ test for independence
	  \item Fisher's exact test
	  \item Measures of association in two-by-two tables
	\end{itemize}
	
\end{small}

This lab generalizes inference for binomial proportions to the setting of two-way contingency tables. Hypothesis testing in a two-way table assesses whether the two variables of interest are associated; this approach can be applied to settings with two or more groups and for responses that have two or more categories. Measures of association in two-by-two tables are also discussed.

The material in this lab corresponds to Sections 8.3 and 8.5 in *OpenIntro Biostatistics*.

### Introduction

*The $\chi^2$ test of independence*

In the $\chi^2$ test of independence, the observed number of cell counts are compared to the number of **expected** cell counts, where the expected counts are calculated under the null hypothesis.

  - $H_0$: the row and column variables are not associated

  - $H_A$: the row and column variables are associated

The expected count for the $i^{th}$ row and $j^{th}$ column is
\[E_{i, j} = \dfrac{(\text{row $i$ total}) \times (\text{column $j$ total}) }{n}, \]
where $n$ is the total number of observations.

Assumptions for the $\chi^2$ test:

  - *Independence*. Each case that contributes a count to the table must be independent of all other cases in the table.
  
  - *Sample size*. Each expected cell count must be greater than or equal to 10. For tables larger than $2 \times 2$, it is appropriate to use the test if no more than 1/5 of the expected counts are less than 5, and all expected counts are greater than 1.

The **$\chi^2$ test statistic** is calculated as
\[\chi^2 = \sum_{i = 1}^r \sum_{j = 1}^c \dfrac{(O_{i, j} - E_{i, j})^2}{E_{i, j}}, \]
and is approximately distributed $\chi^2$ with degrees of freedom $(r - 1)(c - 1)$, where $r$ is the number of rows and $c$ is the number of columns. $O_{i, j}$ represents the observed count in row $i$, column $j$.

For each cell in a table, the **residual** equals
\[\dfrac{O_{i, j} - E_{i, j}}{\sqrt{E_{i,j}}}. \]
Residuals with a large magnitude contribute the most to the $\chi^2$ statistic. If a residual is positive, the observed value is greater than the expected value; if a residual is negative, the observed value is less than the expected.

\vspace{0.5cm}

*Fisher's exact test*

When the expected counts in a two-way table are less than 10, Fisher's exact test is used to compute a $p$-value without relying on the normal approximation. In this course, only the logic behind Fisher's exact test for a $2 \times 2$ table is discussed. In the $2 \times 2$ table case, the hypotheses for Fisher's exact test can be expressed in the same way as for a two-sample test of proportions; the null hypothesis is $H_0: p_1 = p_2$.

The $p$-value is the probability of observing results as or more extreme than those observed under the assumption that the null hypothesis is true.

  - Thus, the $p$-value is calculated by adding together the individual conditional probabilities of obtaining each table that is as or more extreme than the one observed, under the null hypothesis and given that the marginal totals are considered fixed.
  
  - When the marginal totals are held constant, the value of any one cell in the table determines the rest of entries. When marginal totals are considered fixed, each table represents a unique set of results.
  
  - Extreme tables are those which contradict $H_0: p_1 = p_2$.
  
  - A two-sided $p$-value can be calculated by doubling the smaller of the possible one-sided $p$-values; this method is typically used when calculating $p$-values by hand. Another common method is to classify "more extreme" tables as all tables with probabilities less than that of the observed table, in both directions; the $p$-value is the sum of probabilities for the qualifying table.
  
The probability of a particular table (i.e., set of results) can be calculated with the **hypergeometric distribution**.

Let $X$ represent the number of successes in a series of repeated Bernoulli trials, where sampling is done without replacement. Suppose that in the population of size $N$, there are $m$ total successes. What is the probability of observing exactly $k$ successes when drawing a sample of size $n$?


For example, imagine an urn with $m$ white balls and $N - m$ black balls (thus, there are $N$ total balls). Draw $n$ balls without replacement (i.e., a sample of $n$ balls). What is the probability of observing $k$ white balls in the sample? 

The possible results of a sample can be organized in a $2 \times 2$ table:

\begin{table*}[h!]
\begin{center}
\begin{tabular}{l|cc|c} 
   & \textbf{White Ball} & \textbf{Black Ball} & \textbf{Total}\\ \hline
  \textbf{Sampled} & $k$ & \textcolor{gray}{$n - k$}  & $n$  \\
  \textbf{Not Sampled} & \textcolor{gray}{$m - k$} & \textcolor{gray}{$N - n - (m - k)$} & \textcolor{gray}{$N - n$} \\ \hline
  \textbf{Total} & $m$ & $N - m$ & $N$  \\ 
\end{tabular}\\
\end{center}
\end{table*}


The probability of observing exactly $k$ successses in a sample of size $n$ (i.e., $n$ dependent trials) is given by 
\[P(X = k) = \dfrac{{m \choose k} {N - m \choose n-k}}{{N \choose n}}. \]

Hypergeometric probabilities are calculated in \textsf{R} with the use of \texttt{dhyper()} and \texttt{phyper()}. The following code shows how to calculate $P(X = 5)$, $P(X \leq 5)$, and $P(X > 5)$ for $X \sim \text{HGeom}(10, 15, 8)$, where $m = 10$, $N - m = 15$, and $n = 8$. 

```{r}
#probability X equals 5
dhyper(5, 10, 15, 8)

#probability X is less than or equal to 5
phyper(5, 10, 15, 8)

#probability X is greater than 5
phyper(5, 10, 15, 8, lower.tail = FALSE)
```

\vspace{0.5cm}

*Measures of association in two-by-two tables*

Chapter 1 introduced the **relative risk (RR)**, a measure of the risk of a certain event occurring in one group relative to the risk of the event occurring in another group, as a numerical summary for two-by-two ($2 \times 2$) tables. The relative risk can also be thought of as a measure of association.

Consider the following hypothetical two-by-two table. The relative risk of Outcome A can be calculated by using either Group 1 or Group 2 as the reference group:

\begin{table}[h!]
	\centering
	\begin{tabular}{r|rrr}
		\hline
		& Outcome A & Outcome B & Sum\\ 
		\hline
		Group 1 & $a$ & $b$ & $a + b$ \\ 
		Group 2 & $c$ & $d$ & $c + d$ \\
		Sum & $a + c$ & $b + d$ & $a + b + c + d = n$ \\
		\hline
	\end{tabular}	
	\caption{A hypothetical two-by-two table of outcome by group.}
\end{table}


\[RR_{\text{A, comparing Group 1 to Group 2}} = \dfrac{a/(a + b)}{c/(c+d)} \]
\[RR_{\text{A, comparing Group 2 to Group 1}} = \dfrac{c/(c + d)}{a/(a+b)} \]

The relative risk is only valid for tables where the proportions $a/(a + b)$ and $c/(c + d)$ represent the incidence of Outcome A within the populations from which Groups 1 and 2 are sampled.

The **odds ratio (OR)** is a measure of association that remains applicable even when it is not possible to estimate incidence of an outcome from the sample data. The **odds** of Outcome A in Group 1 are $a/b$, while the odds of Outcome A in Group 2 are $c/d$.

\[OR_{\text{A, comparing Group 1 to Group 2}} = \dfrac{a/b}{c/d} = \dfrac{ad}{bc} \]
\[OR_{\text{A, comparing Group 2 to Group 1}} = \dfrac{c/d}{a/b} = \dfrac{bc}{ad} \]

\vspace{0.5cm}

### The $\chi^2$ test of independence

1. In resource-limited settings, single-dose nevirapine (NVP) is given to an HIV-positive woman during birth to prevent mother-to-child transmission of the virus. Exposure of the infant to NVP may foster the growth of more virulent strains of the virus in the child.

    If a child is HIV-positive, should they be treated with NVP or a more expensive drug, lopinavir (LPV)? In this setting, success means preventing a growth of the virus in the child (i.e., preventing virologic failure). The following table contains data from a 2012 study conducted in six African countries and India.\footnote{A. Violari, et al. "Nevirapine versus ritonavir-boosted lopinavir for HIV-infected children." \textit{NEJM} 366: 2380-2389.}
    
    \begin{center}
\begin{tabular}{l|cc|c} 
   & \textbf{NVP} & \textbf{LPV} & \textbf{Total}\\ \hline
  \textbf{Virologic Failure} & 60 & 27 & 87  \\
  \textbf{Stable Disease} & 87 & 113 & 200 \\ \hline
  \textbf{Total} & 147 & 140 & 287  \\ 
\end{tabular}\\
\end{center}

    \vspace{0.5cm}
    
    a) State the null and alternative hypotheses.
    
    b) Calculate the expected cell counts.
    
    c) Check the assumptions for using the $\chi^2$ test.
    
    d) Calculate the $\chi^2$ test statistic.
    
    e) Calculate the $p$-value for the test statistic using \texttt{pchisq()}. The $p$-value represents the probability of observing a result as or more extreme than the sample data.
    
    f) Confirm the results from parts c) and d) using \texttt{chisq.test()}. Note that the value of the test statistic will be slightly different because \textsf{R} is applying a 'continuity correction'.
    
    g) Summarize the conclusions; be sure to include which drug is recommended for treatment, based on the data.
    
    h) Repeat the analysis using inference for the difference of two proportions and confirm that the results are the same.
    
2. In the PREVEND study introduced in Chapter 6, researchers measured various features of study participants, including data on statin use and highest level of education attained. From the data in \texttt{prevend.samp}, is there evidence of an association between statin use and educational level? Summarize the results.

### Fisher's exact test

3. \textit{Clostridium difficile} is a bacterium that causes inflammation of the colon. Antibiotic treatment is typically not effective, particularly for patients who experience multiple recurrences of infection. Infusion of feces from healthy donors has been reported as an effective treatment for recurrent infection. A randomized trial was conducted to compare the efficacy of donor-feces infusion versus vancomycin, the antibiotic typically prescribed to treat \textit{C. difficile }infection. The results of the trial are shown in the following table. 

    \begin{table}[h]
	\centering
	\begin{tabular}{rrr|r}
		\hline
		& Cured & Uncured & Sum \\ 
		\hline
		Fecal Infusion & 13 & 3 & 16 \\ 
		Vancomycin & 4 & 9 & 13 \\ 
		\hline
		Sum & 17 & 12 & 29 \\ 
		\hline
	\end{tabular}
    \end{table}

    a) Can a $\chi^2$ test be used to analyze these results?
    
    b) Researchers are interested in understanding whether fecal infusion is a more effective treatment than vancomycin. Write the null hypothesis and appropriate one-sided alternative hypothesis.
    
    c) Under the assumption that the marginal totals are fixed, enumerate all possible sets of results that are more extreme than what was observed, in the same direction.
    
    d) Calculate the probability of the observed results.
    
    e) Calculate the probability of each set of results enumerated in part c).

    f) Based on the answers in parts d) and e), compute the one-sided $p$-value and interpret the results.
    
    g) Use \texttt{fisher.test( )} to confirm the calculations in part f) and to calculate the two-sided $p$-value.
  

4. Psychologists conducted an experiment to investigate the effect of anxiety on a person's desire to be alone or in the company of others (Schacter 1959; Lehmann 1975). A group of 30 individuals were randomly assigned into two groups; one group was designated the "high anxiety" group and the other the "low anxiety" group. Those in the high-anxiety group were told that in the "upcoming experiment", they would be subjected to painful electric shocks, while those in the low-anxiety group were told that the shocks would be mild and painless.\footnote{Individuals were not actually subjected to electric shocks of any kind}. All individuals were informed that there would be a 10 minute wait before the experiment began, and that they could choose whether to wait alone or with other participants.

    The following table summarizes the results:
  
    \begin{table}[h]
	\centering
	\begin{tabular}{rrr|r}
		\hline
		& Wait Together & Wait Alone & Sum \\ 
		\hline
		High-Anxiety & 12 & 5 & 17 \\ 
		Low-Anxiety & 4 & 9 & 13 \\ 
		\hline
		Sum & 16 & 14 & 30 \\ 
		\hline
	\end{tabular}
    \end{table}


    a) Under the null hypothesis of no association, what are the expected cell counts?
    
    b) Under the assumption that the marginal totals are fixed and the null hypothesis is true, what is the probability of the observed set of results?
    
    c) Enumerate the tables that are more extreme than what was observed, in the same direction. 
    
    d) Conduct a formal test of association for the results and summarize your findings. Let $\alpha = 0.05$.


### Measures of association in two-by-two tables

5. Suppose a study is conducted to assess the association between smoking and cardiovascular disease (CVD). Researchers recruited a group of 231 study participants then categorized them according to smoking and disease status: 111 are smokers, while 40 smokers and 32 non-smokers have CVD. Calculate and interpret the relative risk of CVD.

6. Suppose another study is conducted to assess the association between smoking and CVD, but researchers use a different design: 90 individuals with CVD and 110 individuals without CVD are recruited. 40 of the individuals with CVD are smokers, and 80 of the individuals without CVD are non-smokers.

    a) Is relative risk an appropriate measure of association for these data? Explain your answer.
    
    b) Calculate the odds of CVD among smokers and the odds of CVD among non-smokers.
    
    c) Calculate and interpret the odds ratio of CVD, comparing smokers to non-smokers.
    
    d) What would an odds ratio of CVD (comparing smokers to non-smokers) equal to 1 represent, in terms of the association between smoking and CVD? What would an odds ratio of CVD less than 1 represent?