---
title: "Lab Notes"
author: "Chapter 6"
date: "OpenIntro Biostatistics"

fontsize: 11pt
geometry: margin=1in

output:
  pdf_document:
    includes:
      in_header: ../../header.tex
    fig_width: 6.5
    fig_height: 3.5
---

# Overview

1. Examining Scatterplots
    - *OI Biostat* Section 6.1
    
2. Introduction to Least Squares Regression
    - *OI Biostat* Sections 6.2 and 6.3.1
    
3. Understanding $R^2$
    - *OI Biostat* Section 6.3.2
    
4. Categorical Predictors with Two Levels and Inference in Regression
    - *OI Biostat* Sections 6.3.3 and 6.4

Lab 1 introduces the idea of using a straight line to summarize data that exhibit an approximately linear relationship and the mechanics of fitting and interpreting a line of best fit.

Lab 2 formally introduces the statistical model for least squares regression and discusses the residual plots used to assess the assumptions for linear regression.

Lab 3 explores the idea behind the quantity $R^2$ by sampling observations according to a population regression model with known parameters.

Lab 4 discusses the use of binary categorical predictor variables and the extension of statistical inference to a regression context.

\newpage


# Lab 1: Examining Scatterplots



\newpage

# Lab 2: Introduction to Least Squares Regression



\newpage

# Lab 3: Understanding $R^2$


\newpage

#Lab 4: Categorical Predictors with Two Levels and Inference in Regression